---
abstract: 'Integrate Cairo into the Glib type system'
author:
  - 'gtk2-perl Team <gtk-perl-list at gnome dot org>'
build_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.132830'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Cairo-GObject
no_index:
  directory:
    - t
    - inc
resources:
  MailingList: https://mail.gnome.org/mailman/listinfo/gtk-perl-list
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Cairo-GObject
  homepage: http://gtk2-perl.sourceforge.net/
  license: http://www.gnu.org/licenses/lgpl-2.1.html
  repository: git://git.gnome.org/perl-Cairo-GObject
version: 1.003
